### ISSUE TITLE
Platform request: Sandstorm.io

### ISSUE THREAD

**Issue by ocdtrekkie** [kevguy/Hangout-Reader#1]
I just wanted to float this as an idea to you. I use Sandstorm.io, which is an open source server platform where you can easily host apps and data, and I've moved a lot of the things I used to use Google services for to it, like my Google Drive docs and stuff. I've had a longstanding irritation with how useless a lot of Google Takeout data is without a good way to browse it, so I think this project is pretty cool.

I would really love if there was a Sandstorm package for this that I could move my Google Hangouts data into and store on the server. The cool thing about Sandstorm is that it handles things like login, sharing, and user management, and each file (called grains in Sandstorm) is a completely separate copy of the app in question. So it would theoretically take very little to make a project like this work in Sandstorm, as you wouldn't have to worry about any of those sorts of details. The only thing you would need to do is have a mode of the app that stored and retrieved your Hangouts data from the /var folder, which is the only folder which is writeable in a Sandstorm app. And since people can either self-host Sandstorm or use Sandstorm.io's public hosting service which includes a free tier, you get all the perks of running a "cloud service" without having to maintain infrastructure or the costs yourself.

If you want to try a demo of Sandstorm, you can do so at https://demo.sandstorm.io

**Comment by kevguy** [comment]
I guess when people use this thing their primary concern is privacy, so I have my mind set on providing as much transparency as possible, like letting them run this locally etc. 

Still, I think what you said is kinda interesting, so if you want we can collaborate on doing this too!

**Comment by ocdtrekkie** [comment]
Yeah, I'm just thinking an expansion out to being somewhere they can store *and* read their logs is probably worthwhile. Ideally, such an app could be installed locally, or packaged for app platforms like Sandstorm.io (or Cloudron.io, a similar platform).

While I have done some work packaging existing software for Sandstorm, and I write a .NET home automation program in my spare time, I am not much of a 'developer', and probably would not be able to contribute significantly enough for any such project to be considered a 'collaboration'.
